"""Se crea tabla Rol

Revision ID: 43e80ed80bf0
Revises: 45d88619cd76
Create Date: 2026-04-07 10:52:51.489115

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e80ed80bf0'
down_revision: Union[str, Sequence[str], None] = '45d88619cd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rol_id')
    )
    op.create_index(op.f('ix_rol_rol'), 'rol', ['rol'], unique=False)
    op.create_index(op.f('ix_rol_rol_id'), 'rol', ['rol_id'], unique=False)
    op.create_index(op.f('ix_rol_role_id'), 'rol', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rol_role_id'), table_name='rol')
    op.drop_index(op.f('ix_rol_rol_id'), table_name='rol')
    op.drop_index(op.f('ix_rol_rol'), table_name='rol')
    op.drop_table('rol')
    # ### end Alembic commands ###
