"""Se crea tabla Permiso

Revision ID: 45d88619cd76
Revises: 6a17056d9c68
Create Date: 2026-04-06 15:36:08.682406

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d88619cd76'
down_revision: Union[str, Sequence[str], None] = '6a17056d9c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('permiso', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('permiso_id')
    )
    op.create_index(op.f('ix_permiso_permiso'), 'permiso', ['permiso'], unique=False)
    op.create_index(op.f('ix_permiso_permiso_id'), 'permiso', ['permiso_id'], unique=False)
    op.create_index(op.f('ix_permiso_tracking_id'), 'permiso', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permiso_tracking_id'), table_name='permiso')
    op.drop_index(op.f('ix_permiso_permiso_id'), table_name='permiso')
    op.drop_index(op.f('ix_permiso_permiso'), table_name='permiso')
    op.drop_table('permiso')
    # ### end Alembic commands ###
