"""Se crea tabla Pantalla

Revision ID: 6a17056d9c68
Revises: 8524b41a89ce
Create Date: 2026-04-01 11:55:00.508872

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a17056d9c68'
down_revision: Union[str, Sequence[str], None] = '8524b41a89ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantalla',
    sa.Column('pantalla_id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('pantalla', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.modulo_id'], ),
    sa.PrimaryKeyConstraint('pantalla_id')
    )
    op.create_index(op.f('ix_pantalla_modulo_id'), 'pantalla', ['modulo_id'], unique=False)
    op.create_index(op.f('ix_pantalla_pantalla'), 'pantalla', ['pantalla'], unique=False)
    op.create_index(op.f('ix_pantalla_tracking_id'), 'pantalla', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pantalla_tracking_id'), table_name='pantalla')
    op.drop_index(op.f('ix_pantalla_pantalla'), table_name='pantalla')
    op.drop_index(op.f('ix_pantalla_modulo_id'), table_name='pantalla')
    op.drop_table('pantalla')
    # ### end Alembic commands ###
