"""Se agrega la tabla permiso_usuario

Revision ID: 81644fc250ac
Revises: 2a9e320ec659
Create Date: 2026-04-22 11:18:24.322386

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81644fc250ac'
down_revision: Union[str, Sequence[str], None] = '2a9e320ec659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso_usuario',
    sa.Column('permiso_usuario_id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pantalla_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('permiso', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pantalla_id'], ['pantalla.pantalla_id'], ),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.permiso_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('permiso_usuario_id')
    )
    op.create_index(op.f('ix_permiso_usuario_pantalla_id'), 'permiso_usuario', ['pantalla_id'], unique=False)
    op.create_index(op.f('ix_permiso_usuario_permiso_id'), 'permiso_usuario', ['permiso_id'], unique=False)
    op.create_index(op.f('ix_permiso_usuario_tracking_id'), 'permiso_usuario', ['tracking_id'], unique=False)
    op.create_index(op.f('ix_permiso_usuario_usuario_id'), 'permiso_usuario', ['usuario_id'], unique=False)
    op.alter_column('permiso', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('permiso', 'fecha_modificacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('rol', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('rol', 'fecha_modificacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rol', 'fecha_modificacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('rol', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('permiso', 'fecha_modificacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('permiso', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_permiso_usuario_usuario_id'), table_name='permiso_usuario')
    op.drop_index(op.f('ix_permiso_usuario_tracking_id'), table_name='permiso_usuario')
    op.drop_index(op.f('ix_permiso_usuario_permiso_id'), table_name='permiso_usuario')
    op.drop_index(op.f('ix_permiso_usuario_pantalla_id'), table_name='permiso_usuario')
    op.drop_table('permiso_usuario')
    # ### end Alembic commands ###
