"""init

Revision ID: 8524b41a89ce
Revises: 
Create Date: 2026-03-31 12:13:14.069301

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8524b41a89ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulo',
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('modulo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('modulo_id')
    )
    op.create_index(op.f('ix_modulo_modulo'), 'modulo', ['modulo'], unique=False)
    op.create_index(op.f('ix_modulo_modulo_id'), 'modulo', ['modulo_id'], unique=False)
    op.create_index(op.f('ix_modulo_tracking_id'), 'modulo', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modulo_tracking_id'), table_name='modulo')
    op.drop_index(op.f('ix_modulo_modulo_id'), table_name='modulo')
    op.drop_index(op.f('ix_modulo_modulo'), table_name='modulo')
    op.drop_table('modulo')
    # ### end Alembic commands ###
