"""Se modifica la columna fecha_registro de la tabla Pantalla

Revision ID: 88c77a729dda
Revises: af0308f1ac8e
Create Date: 2026-04-20 11:22:27.346533

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88c77a729dda'
down_revision: Union[str, Sequence[str], None] = 'af0308f1ac8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantalla', sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
    op.drop_column('pantalla', 'fecha_registro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantalla', sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('pantalla', 'fecha_creacion')
    # ### end Alembic commands ###
