"""Se crean las tablas de Usuario, User y Membership

Revision ID: af0308f1ac8e
Revises: d3b5f84b3ad4
Create Date: 2026-04-14 10:45:38.705265

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0308f1ac8e'
down_revision: Union[str, Sequence[str], None] = 'd3b5f84b3ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('membership',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('esta_bloqueado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_membership_email'), 'membership', ['email'], unique=True)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=True)
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('apellido_paterno', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('apellido_materno', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('domicilio', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('user_id', name='uq_usuario_user')
    )
    op.create_index(op.f('ix_usuario_user_id'), 'usuario', ['user_id'], unique=True)
    op.create_index(op.f('ix_usuario_usuario_id'), 'usuario', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_user_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_email'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
